brew 'agda'
brew 'coq'
brew 'elm'
brew 'emacs'
brew 'git'
brew 'gist'
brew 'gpg2'
brew 'haskell-stack' if OS.mac? # Broken in Linuxbrew.
brew 'hub'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'mr'
brew 'neovim'
brew 'nim'
brew 'ocaml'
brew 'peco'
brew 'pinentry-mac' if OS.mac?
brew 'python'
brew 'purescript'
brew 'ripgrep'
brew 'rlwrap'
brew 'scala'
brew 'shellcheck'
brew 'sphinx-doc'
brew 'tidy-html5'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watchman'
brew 'zsh'

if OS.mac?
  brew 'bash'
  brew 'bash-completion@2'

  cask '1password'
  cask 'adobe-digital-editions'
  cask 'android-file-transfer'
  cask 'bittorrent'
  cask 'caffeine'
  cask 'docker'
  cask 'dropbox'
  cask 'firefox'
  cask 'flux'
  cask 'font-fira-code'
  cask 'google-chrome'
  cask 'google-cloud-sdk'
  cask 'google-drive-file-stream'
  cask 'iina'
  cask 'iterm2'
  cask 'java'
  cask 'karabiner-elements'
  cask 'keybase'
  cask 'kindle'
  cask 'kitty'
  cask 'psequel'
  cask 'rescuetime'
  cask 'sequel-pro'
  cask 'skype'
  cask 'spectacle'
  cask 'visual-studio-code'
  cask 'zotero'
end

# vim: filetype=ruby
