brew 'emacs'
brew 'git'
brew 'haskell-stack' if false # Broken in brew
brew 'mr'
brew 'neovim'
brew 'python'
brew 'ripgrep'
brew 'rlwrap'
brew 'tmux'
brew 'zsh'

if OS.mac?
  brew 'bash'
  brew 'bash-completion@2'

  cask '1password'
  cask 'adobe-digital-editions'
  cask 'android-file-transfer'
  cask 'bittorrent'
  cask 'caffeine'
  cask 'docker'
  cask 'dropbox'
  cask 'firefox'
  cask 'flux'
  cask 'font-fira-code'
  cask 'google-chrome'
  cask 'google-cloud-sdk'
  cask 'google-drive-file-stream'
  cask 'iina'
  cask 'iterm2'
  cask 'java'
  cask 'karabiner-elements'
  cask 'keybase'
  cask 'kindle'
  cask 'kitty'
  cask 'rescuetime'
  cask 'skype'
  cask 'spectacle'
  cask 'visual-studio-code'
  cask 'zotero'
end

# vim: filetype=ruby
