owner = "steshaw"
fullName = "Steven Shaw"
email = "steven@steshaw.org"
license = "MIT"

cabal = true
stack = true

lib = true
exe = true
test = true
bench = true

github = true
noUpload = true
private = true
# gitignore =      # list of additional entries to be added in .gitignore
#     [ "build"
#     , "result"
#     ]

# CI.
githubActions = true
travis = false
appveyor = false

# List of additional GHC versions to support besides 8.8.3.
# Run the 'summon show ghc' command to see the list of all supported GHC versions.
# ghcVersions = ["8.4.4", "8.6.5"]

# List of default-extensions in the .cabal file
# extensions = [ "ConstraintKinds"
#              , "DeriveGeneric"
#              , "GeneralizedNewtypeDeriving"
#              , "InstanceSigs"
#              , "KindSignatures"
#              , "LambdaCase"
#              , "OverloadedStrings"
#              , "RecordWildCards"
#              , "ScopedTypeVariables"
#              , "StandaloneDeriving"
#              , "TupleSections"
#              , "TypeApplications"
#              , "ViewPatterns"
#              ]

# List of additional files to add after creating the project
# files =
#     [ { path = ".stylish-haskell.yaml"
#       , url  = "https://raw.githubusercontent.com/kowainik/org/master/.stylish-haskell.yaml"
#       }
#     , { path = ".github/CODEOWNERS"
#       , raw  = "*  @kowainik"
#       }
#     , { path  = "src/Foo.hs"
#       , local = "/home/user/.default/Foo.hs"
#       }
#     ]

# Alternative Prelude to be used instead of the default one if you prefer
# [prelude]
#     package = "relude"
#     module  = "Relude"
