[options]
  # Dark themes: molokai jellybeans hybrid desert evening SpaceVim.
  colorscheme = "hybrid"
  colorscheme_bg = 'dark'
  enable_guicolors = true

  # statusline
  buffer_index_type = 4
  enable_statusline_mode = false
  statusline_inactive_separator = 'bar'
  statusline_separator = 'arrow'

  enable_tabline_filetype_icon = false # False for nerd fonts.

  project_rooter_automatically = 0

  bootstrap_before = "myspacevim#before"
  bootstrap_after =  "myspacevim#after"

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart" # "cycle"
  [options]
    autocomplete_method = "coc"

[[layers]]
  name = "lsp"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 30

[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = false

[[custom_plugins]]
  name = "LnL7/vim-nix"
  merged = false

[[custom_plugins]]
  name = 'idris-hackers/idris-vim'
  merged = false

# ---------------------------------------------------------------------
# Org mode {
# ---------------------------------------------------------------------

[[custom_plugins]]
  name = 'jceb/vim-orgmode'
  merged = false

[[custom_plugins]]
  name = 'tpope/vim-speeddating' # Required dependency of vim-orgmode.
  merged = false

[[custom_plugins]]
  name = 'steshaw/vim-timedot'
  merged = false

## SyntaxRange allows timedot in src blocks.
## See .config/nvim/after/syntax/org.vim
#[[custom_plugins]]
#  name = 'vim-scripts/SyntaxRange'

# } --------------------------------------------------------------------
