#!/usr/bin/env bash

if true || [[ ${SHELLY_OS} == 'darwin' ]]; then
  isBash && sourceExists ~/.iterm2_shell_integration.bash
  isZsh && sourceExists ~/.iterm2_shell_integration.zsh
fi

iterm-colour() {
  if [[ $ITERM_COLOUR == 'dark' ]]; then
    ITERM_COLOUR='light'
    it2setcolor preset 'Light Background'
  else
    ITERM_COLOUR='dark'
    it2setcolor preset 'Dark Background'
  fi
}
