#!/usr/bin/env bash

set -euo pipefail

usage() {
  echo "usage $0: install"
  exit 2
}

pkgs=(
  doom-emacs
  dotnet
)

install_dir=../local
mkdir -p $install_dir

if [[ $# -eq 1 && $1 == install ]]; then
  stow --target $install_dir --restow "${pkgs[@]}"
else
  usage
fi
