#!/usr/bin/env bash

set -eu

which apt-get >/dev/null 2>&1 && sudo apt-get install myrepos git

mr bootstrap https://raw.githubusercontent.com/steshaw/shelly/master/dotfiles/.mrconfig

SHELLY_HOME=~/Projects/shelly
PATH=${SHELLY_HOME}/bin:${PATH}
ShellyLinkDotFiles

generate-ssh-key
github-add-key
bitbucket-add-key
