#!/usr/bin/env bash

set -eu

echo Bootstrapping shelly...

# FIXME: Need to ensure myrepos and git on other platforms.
hash git python || (
  echo "Please ensure that git and python are installed" >&2
  exit 1
)

SHELLY_HOME=~/Projects/steshaw/shelly

if [[ ! -d $SHELLY_HOME ]]; then
  git clone https://github.com/steshaw/shelly.git "$SHELLY_HOME"
  (
    cd "$SHELLY_HOME"
    git remote set-url origin git@github.com:steshaw/shelly.git
  )
fi

PATH=${SHELLY_HOME}/bin:${PATH}
ShellyLinkDotFiles

if [[ ! -f ~/.ssh/id_rsa ]]; then
  echo Generate ssh key...
  generate-ssh-key
  echo
fi
