tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "mas"
brew "koekeishiya/formulae/skhd"
cask "amethyst"
cask "caffeine"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "nightfall"
cask "postman"
cask "skype"
cask "spectacle"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "HP Easy Scan", id: 967004861
mas "Tailscale", id: 1475387142
