#!/bin/bash

# Bail if HOMEBREW already configured.
# This makes a _huge_ difference to shell start times (such as well
# opening a new tab in iTerm).
[[ -n ${HOMEBREW_PREFIX} ]] && return

prettyPaths '010-homebrew: before'

initBrew() {
  local dir=$1
  local brew=$dir/bin/brew
  if [[ -x $brew ]]; then
    # shellcheck disable=SC2046
    eval $($brew shellenv)
    return 0
  else
    return 1
  fi
}

initBrew /home/linuxbrew/.linuxbrew ||
  initBrew ~/.linuxbrew ||
  initBrew /opt/homebrew ||
  initBrew /usr/local

unset initBrew

prettyPaths '010-homebrew: after'
