command_timeout = 1000

#
# Comment out prompt with pipes. e.g.
#   ╭─
#   ╰─$
#
# It currently causes breaks wrapping lines beyond the edge of the terminal.
#
# See:
#  "Unicode characters break long command wrapping"
#   https://github.com/starship/starship/issues/3250

#format = """
#[╭─](green)\
#format = """
#[╭─](green)\
#$username\
#$hostname\
#$shlvl\
#$singularity\
#$kubernetes\
#$directory\
#$vcsh\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$git_status\
#$hg_branch\
#$docker_context\
#$package\
#$cmake\
#$cobol\
#$dart\
#$deno\
#$dotnet\
#$elixir\
#$elm\
#$erlang\
#$golang\
#$helm\
#$java\
#$julia\
#$kotlin\
#$lua\
#$nim\
#$nodejs\
#$ocaml\
#$perl\
#$php\
#$pulumi\
#$purescript\
#$python\
#$rlang\
#$red\
#$ruby\
#$rust\
#$scala\
#$swift\
#$terraform\
#$vlang\
#$vagrant\
#$zig\
#$nix_shell\
#$conda\
#$memory_usage\
#$aws\
#$gcloud\
#$openstack\
#$azure\
#$env_var\
#$crystal\
#$custom\
#$sudo\
#$cmd_duration\
#$line_break\
#[╰─](green)\
#$jobs\
#$battery\
#$time\
#$status\
#$shell\
#$character"""

#format = '$all'


[aws]
disabled = true

[gcloud]
disabled = true

# Disable jobs while broken on macOS.
# https://github.com/starship/starship/issues/3096#issuecomment-1116090294
[jobs]
disabled = true

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_symbol = "…/"
truncation_length = 5
repo_root_style = 'bold cyan'
use_os_path_sep = false

[username]
show_always = true
style_user = "cyan"
format = "[$user@]($style)"

[hostname]
ssh_only = false
style = "cyan"
format = "[$hostname]($style):"
