#!/usr/bin/env bash

#
# Should be suitable for bash and zsh.
#

Echo "Executing shrc"

# =========================================================================

setEditor() {
  editor=$1
  Echo "Trying $editor"
  if has "$editor"; then
    export VISUAL
    VISUAL=$(command -v "$editor")
    Echo "VISUAL=$VISUAL"
    return 0
  else
    Echo "We don't have $editor"
    return 1
  fi
}

unset EDITOR
unset VISUAL
setEditor nvim || setEditor vim
[[ -n $VISUAL ]] && export EDITOR=$VISUAL

set -o vi 2>/dev/null || Echo 'Cannot set vi editing mode'

# =========================================================================
# Aliases

# This also ensures that we switch the "standard" oh-my-zsh ls aliases
# as we want the shortest one for the most common command! i.e. l.

enable_lsd=1
if [[ $enable_lsd -ne 0 ]] && has lsd; then
  alias ls=lsd
elif ls --color >/dev/null 2>&1; then
  # GNU ls.
  alias ls='ls --color -F'
else
  # macOS/Darwin/BSD ls.
  export CLICOLOR=
  eval "$(dircolors)"
  LSCOLORS=$(gnu2bsd-colors)
  export LSCOLORS
  alias ls='ls -F'
fi

alias l='ls -lh'
alias ll='l -A' # and prefer -A to -a. Don't need '.' and '..' often.
alias la='l -a'

alias wi='type -ap' # Where are all matching commands on PATH.

# Make file ops safer.
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias cx='chmod +x'
alias cw='chmod +w'

alias history-reload='history -a && history -r'

alias vo="edit-overlay"

alias sghci='stack exec -- ghci'

alias pj='pijul'

alias k8s='kubectl'
alias kube='kubectl'

alias clear='clear -x'

# Some git aliases from oh-my-zsh and more.
alias gst='git status'
alias ga='git add'
alias gaa='git add --all'
alias gitp='git push'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gc='git commit -v'
alias gd='git diff'
alias gds='git diff --staged'
alias grh='git reset HEAD'

alias path='ppath'
alias cdpath='echo $CDPATH | tr : "\n"'

if [[ ${SHELLY_OS} != 'darwin' ]]; then
  alias pbcopy='xsel --clipboard --input'
  alias pbpaste='xsel --clipboard --output'
fi

alias sml='rlwrap sml'
alias ocaml='rlwrap ocaml'

# =========================================================================

# This cdpath array works out-of-box for zsh.
# For bash, it's processed into CDPATH.
cdpath=(
  .
  ~/Code
  ~/Code/steshaw
)

# Add all directories in `~/Code`.
for dir in ~/Code/*; do
  [[ -d ${dir} && ${dir} != ~/Code/steshaw ]] && cdpath=("${cdpath[@]}" "${dir}")
done

if isBash; then
  CDPATH=$(IFS=':'; echo "${cdpath[*]}")
  unset cdpath
fi

# =========================================================================

#
# Source etc/shrc.d/*
#
for file in "$SHELLY_HOME"/etc/shrc.d/*; do
  sourceExists "${file}"
done

# =========================================================================

sourceExists ~/.travis/travis.sh # for travis gem
