#!/usr/bin/env sh

if [ -n "$ZSH_VERSION" ]; then
  test -r /Users/steshaw/.opam/opam-init/init.zsh &&
    . /Users/steshaw/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
else
  test -r /Users/steshaw/.opam/opam-init/init.sh &&
    . /Users/steshaw/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
fi
