#!/usr/bin/env bash

#
# Should be suitable for bash and zsh.
#

Echo "Executing shrc"

# =========================================================================

setEditor() {
  editor=$1
  Echo "Trying $editor"
  if has "$editor"; then
    export VISUAL
    VISUAL=$(command -v "$editor")
    Echo "VISUAL=$VISUAL"
    return 0
  else
    Echo "We don't have $editor"
    return 1
  fi
}

unset EDITOR
unset VISUAL
setEditor nvim || setEditor vim
[[ -n $VISUAL ]] && export EDITOR=$VISUAL

set -o vi 2>/dev/null || Echo 'Cannot set vi editing mode'

# =========================================================================
# Aliases

# This also ensures that we switch the "standard" oh-my-zsh ls aliases
# as we want the shortest one for the most common command! i.e. l.

enable_exa=1
enable_lsd=0

if [[ $enable_exa -ne 0 ]] && has exa; then
  alias ls='exa --classify'
  alias l='ls --long'
  alias ll='l --all'
  # Fallback to GNU ls.
  alias la='ll --all'
else
  if [[ $enable_lsd -ne 0 ]] && has lsd; then
    alias ls=lsd
  elif ls --color >/dev/null 2>&1; then
    # GNU ls.
    alias ls='ls --color --classify'
  else
    # macOS/Darwin/BSD ls.
    export CLICOLOR=
    eval "$(dircolors)"
    LSCOLORS=$(gnu2bsd-colors)
    export LSCOLORS
    alias ls='ls -F'
  fi

  alias l='ls -l --human-readable'
  alias ll='l --almost-all' # and prefer -A to -a. Don't need '.' and '..' often.
  alias la='l --all'
fi

alias wi='type -ap' # Where are all matching commands on PATH.

# Make file ops safer.
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias cx='chmod +x'
alias cw='chmod +w'

alias history-reload='history -a && history -r'

alias vo="edit-overlay"

alias sghci='stack exec -- ghci'

alias pj='pijul'

alias k8s='kubectl'
alias kube='kubectl'

alias clear='clear -x'

# Some git aliases from oh-my-zsh and more.
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gitp='git push'
alias gp='git push'
alias gpfl='git push --force-with-lease'
alias grh='git reset HEAD'
alias gst='git status'

alias path='ppath'
alias cdpath='echo $CDPATH | tr : "\n"'

if [[ ${SHELLY_OS} != 'darwin' ]]; then
  alias pbcopy='xsel --clipboard --input'
  alias pbpaste='xsel --clipboard --output'
fi

alias sml='rlwrap sml'
alias ocaml='rlwrap ocaml'

# =========================================================================

cdpath-update() {
  # This cdpath array works out-of-box for zsh.
  # For bash, it's processed into CDPATH.
  cdpath=(
    .
  )

  cached=~/.cache/shelly/code_dirs.txt
  find_code_dirs() {
    find ~/Code -maxdepth 4 -type d -name .git 2>/dev/null |
      perl -pe 's~/[^/]*/.git$~~' |
      grep -v -E 'nvim.mine|\.archive|node_modules' |
      sort -u
  }
  cdpath-load() {
    while read -r dir; do
      [[ -d ${dir} && ${dir} ]] && cdpath=("${cdpath[@]}" "${dir}")
    done <${cached}

    if isBash; then
      CDPATH=$(IFS=':'; echo "${cdpath[*]}")
      unset cdpath
    fi
  }
  cdpath-write-cache() {
    mkdir -p "$(dirname ${cached})"
    find_code_dirs >|${cached}
  }
  cdpath-refresh() {
    cdpath-write-cache
    cdpath-load
  }
  cdpath-check-cache() {
    # Write a new cache when expired or non-existant.
    # Cache for 5 hours
    hours=5
    minutes=$((hours * 60))
    if [[ ! -f ${cached} || -n $(find ${cached} -mmin +${minutes}) ]]; then
      cdpath-write-cache
    fi
  }
  cdpath-check-cache
  cdpath-load
}
cdpath-update

# =========================================================================

#
# Source etc/shrc.d/*
#
for file in "$SHELLY_HOME"/dotfiles/.config/shellyrc.d/*; do
  sourceExists "${file}"
done

# =========================================================================

sourceExists ~/.travis/travis.sh # for travis gem
