[aws]
disabled = true

[character]
format = "[╰─](green)$symbol "
success_symbol = "[\\$](bold green) "
error_symbol = "[✗](bold red) "

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_symbol = "…/"
truncation_length = 5

[username]
show_always = true
style_user = "cyan"
format = "[╭─](green)[$user@]($style)"

[hostname]
ssh_only = false
style = "cyan"
format = "[$hostname]($style):"
