[aws]
disabled = true

[character]
format = "[╰─](green)$symbol "

[directory]
truncation_symbol = "…/"
style = "bold blue"

[username]
show_always = true
style_user = "cyan"
format = "[╭─](green)[$user@]($style)"

[hostname]
ssh_only = false
style = "cyan"
format = "[$hostname]($style):"
