nix:
  enable: false
templates:
  params:
    author-email: steven@steshaw.org
    copyright: (c) 2019, Steven Shaw
    category: Example
    github-username: steshaw
    author-name: Steven Shaw
    license: MIT
