#!/usr/bin/env bash

if [[ -d /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk ]]; then
  CLOUD_SDK_HOME=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk
elif [[ -d /usr/lib/google-cloud-sdk ]]; then
  CLOUD_SDK_HOME=/usr/lib/google-cloud-sdk
else
  return
fi

if isBash; then
  false && sourceExists "${CLOUD_SDK_HOME}/path.bash.inc"
  sourceExists "${CLOUD_SDK_HOME}/completion.bash.inc"
elif isZsh; then
  false && sourceExists "${CLOUD_SDK_HOME}/path.zsh.inc"
  if [[ -r "${CLOUD_SDK_HOME}/completion.zsh.inc" ]]; then
    sourceExists "${CLOUD_SDK_HOME}/completion.zsh.inc"
  else
    # Try to use bash completion script.
    sourceExists "${CLOUD_SDK_HOME}/completion.bash.inc"
  fi
else
  Echo 'Warning: no completion for google-cloud-sdk for your shell'
fi
