#!/usr/bin/env bash

CLOUD_SDK_HOME=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk

if isBash; then
  false && sourceExists "${CLOUD_SDK_HOME}/path.bash.inc"
  sourceExists "${CLOUD_SDK_HOME}/completion.bash.inc"
elif isZsh; then
  false && sourceExists "${CLOUD_SDK_HOME}/path.zsh.inc"
  sourceExists "${CLOUD_SDK_HOME}/completion.zsh.inc"
else
  Echo 'Warning: no completion for google-cloud-sdk for your shell'
fi
