#!/usr/bin/env bash

if has brew; then
  HAXE_STD_PATH="$(brew --prefix)/lib/haxe/std"
  if [[ -d ${HAXE_STD_PATH} ]]; then
    export HAXE_STD_PATH
    macos-sync-env HAXE_STD_PATH
  fi
fi

#
# NekoVM
#
#nekoLib="${HOME}/.shelly/local/nekovm-trunk/lib/neko"
#[[ -d $nekoLib ]] && export NEKOPATH=${nekoLib}
