#!/usr/bin/env bash

if [[ "$(uname)" = 'Darwin' ]]; then
  JAVA_HOME=$(/usr/libexec/java_home)
  export JAVA_HOME
  macos-sync-env JAVA_HOME

  SwitchJDK() {
    if [[ $# -ne 1 ]]; then
      echo "usage: SwitchJDK 1.7|1.8" >&2
    else
      JAVA_HOME=$(/usr/libexec/java_home -v "$1")
      export JAVA_HOME
      macos-sync-env JAVA_HOME
    fi
  }
fi
