#!/usr/bin/env bash

if [[ -d /Applications/ZeroTurnaround/JRebel ]]; then
  export REBEL_HOME=/Applications/ZeroTurnaround/JRebel
  export REBEL_JAR=$REBEL_HOME/jrebel.jar
  export WITH_REBEL="-Drebel.license=${HOME}/Downloads/jrebel.lic -noverify -javaagent:$REBEL_JAR"
fi
