templates:
  params:
    author-name: Steven Shaw
    author-email: steven@steshaw.org
    # Using "license" here does not work. We'd need to provide an alternative
    # LICENSE file anyhow...
    license: ISC
    copyright: (c) 2018, Steven Shaw
    github-username: steshaw
    category: Example

ghc-options:
  "$locals": -optP-Wno-nonportable-include-path

extra-include-dirs:
- /usr/local/opt/openssl/include

extra-lib-dirs:
- /usr/local/opt/openssl/lib
