#!/usr/bin/env bash

set -euo pipefail

for pkg in "$@"; do
  echo Uninstalling $pkg ...
  brew uninstall $pkg
  deps=$(join <(brew leaves) <(brew deps $pkg))
  if [[ -z $deps ]]; then
    echo No dependencies
  else
    echo "Uninstalling dependencies $deps ..."
    # shellcheck disable=SC2086
    brew uninstall $deps
  fi
done
