#!/usr/bin/env bash

set -euo pipefail

case $(uname) in
  Darwin)
    sudo killall -HUP mDNSResponder
    ;;
  Linux)
    if [[ -f /etc/NIXOS ]]; then
      sudo systemctl restart nscd.service
    else
      sudo systemd-resolve --flush-caches
    fi
    ;;
  *)
    echo "Warning: dns-flush for $(uname)"
esac
