#!/usr/bin/env bash

set -euo pipefail

if [[ ${1:-} == '--tty' ]]; then
  unset DISPLAY
  shift
fi

if [[ -n ${DISPLAY:-} ]]; then
  # Attempt to open in the X Emacs.
  # Fall back on `e --tty`.
  emacsclient \
    --no-wait \
    --alternate-editor='e --tty' \
    "$@"
else
  # Attempt to use the Emacs daemon or start if necessary.
  emacsclient --tty --alternate-editor='' "$@"
fi
