#!/usr/bin/env bash
#
# Rename given files with modification date.
#
# e.g. foo.txt -> 2019-10-01-013534-foo.txt
#

set -euo pipefail

for file_path in "$@"; do
  mod_epoch=$(stat --format=%Y "${file_path}")
  prefix=$(date "--date=@${mod_epoch}" --utc +%Y-%m-%d-%H%M%S)
  dir_name=$(dirname "$file_path")
  file_name=$(basename "$file_path")
  mv -iv "${file_path}" "${dir_name}/${prefix}-${file_name}"
done
