#!/usr/bin/env bash

set -euo pipefail

if [[ $# -eq 0 ]]; then
  key_type='ed25519'
  file="id_${key_type}"
  comment="${USER}@$(hostname -s)"
elif [[ $# -eq 1 ]]; then
  key_type=$1
  file="id_${key_type}"
  comment="${USER}@$(hostname -s)"
elif [[ $# -eq 2 ]]; then
  key_type=$1
  purpose=$2
  file="${purpose}_${key_type}"
  comment="${USER}@$(hostname -s) — ${purpose}"
else
  script_name=$(basename "$0")
  echo "usage: ${script_name} [key-type [purpose]]" >&2
  exit 2
fi

set -x
ssh-keygen \
  -f "${file}" \
  -t ${key_type} \
  -b 4096 \
  -C "${comment}"
