#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "$0")

if [[ $# -eq 0 ]]; then
  echo "usage: $script_name repo (i.e. leanprover/lean4) [git arguments]"
  exit 2
fi

# ty : 'ssh' | 'https'
ty='ssh'
ty='https'

arg=$1
repo_path=$arg
repo_path=${repo_path#https://}
repo_path=${repo_path#git@}
repo_path=${repo_path%.git}
repo_path=${repo_path%#*}
repo_path=${repo_path%/}
repo_path=${repo_path/://}
repo_path=${repo_path%*/*/*/}
repo_path=${repo_path%%/blob/*} # For GitHub
repo_path=${repo_path%%/tree/*} # For GitHub
repo_path=${repo_path%%/-/tree/*} # For GitLab
repo_path=${repo_path%%/src/*} # For Bitbucket
repo_path=${repo_path/\/_git/} # For ADO
repo_path=${repo_path/\/MineStar%20Solution%20Train/\/mst} # For ADO
repo_path=${repo_path/\/Cat%20OS%20Platform/\/catos} # For ADO
shift

IFS=/ read -r -a fields <<<"$repo_path"
case ${#fields[@]} in
  1)
    host='github.com'
    org=${USER}
    repo=${fields[0]}
    ;;
  2)
    host='github.com'
    org=${fields[0]}
    repo=${fields[1]}
    ;;
  *)
    host=${fields[0]}
    org=${fields[1]}
    repo=${fields[*]:2}
    repo=${repo// /\/} # Spaces back to / directory separator
    ;;
esac

# Remove tidle ~
org=${org/\~/}

user='git'
short_org=$org
case $org in
  input-output-hk) short_org='io';;
  io) org='input-output-hk';;
  ModusCreateOrg) short_org='modus';;
  cat-aa) short_org='cat';;
  modus) org='ModusCreateOrg';;
esac

cd "${SHELLY_CODE_DIR}"

dir="${short_org}/${repo}"
if [[ -d $dir ]]; then
  echo "$dir already exists"
  exit 1
fi

if [[ $short_org == 'cat' ]]; then
  # ADO like to receive the full URL.
  git clone "$arg" "${dir}/main"
else
  if [[ $ty == 'ssh' ]]; then
    git clone "$@" "${user}@${host}:${org}/${repo}.git" "${dir}"
  else
    # ty = 'https'
    git clone "$@" "https://${host}/${org}/${repo}.git" "${dir}"
  fi
fi
