#!/usr/bin/env bash

set -euo pipefail

indent() {
  sed -e 's/^/  /'
}

method1() {
  remote=$1
  branch=$2

  if git show-ref --verify --quiet "refs/heads/${branch}"; then
    echo branch exists
    git branch --set-upstream-to="${remote}" "${branch}"
  else
    echo branch does not exist
    git branch --track "${branch}" "${remote}"
  fi
}

method2() {
  remote=$1
  branch=$2

  echo git switch -t -C "${branch}" "$remote"
  echo git pull
}

method3() {
  remote=$1
  branch=$2
  echo git checkout --track "$remote"
}

for remote in $(git branch -r | grep -v '/HEAD'); do
  branch=${remote#origin/}
  echo "remote=$remote"
  echo "branch=$branch"
  echo Method1
  method1 "$remote" "$branch" | indent

  echo Method 2
  method2 "$remote" "$branch" | indent

  echo Method 3
  method3 "$remote" "$branch" | indent
done
