#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "$0")

if [[ $# -ne 1 ]]; then
  echo "usage: $script_name repo (i.e. leanprover/lean4)"
  exit 2
fi

repo_path=${1#https://}
repo_path=${repo_path#git@}
repo_path=${repo_path%.git}
repo_path=${repo_path%#*}
repo_path=${repo_path%/}
repo_path=${repo_path/://}
repo_path=${repo_path%*/*/*/}
repo_path=${repo_path%%/blob/*} # For GitHub
repo_path=${repo_path%%/tree/*} # For GitHub
repo_path=${repo_path%%/-/tree/*} # For GitLab
repo_path=${repo_path%%/src/*} # For Bitbucket

IFS=/ read -r -a fields <<<"$repo_path"
case ${#fields[@]} in
  1)
    host='github.com'
    org=${USER}
    repo=${fields[0]}
    ;;
  2)
    host='github.com'
    org=${fields[0]}
    repo=${fields[1]}
    ;;
  *)
    host=${fields[0]}
    org=${fields[1]}
    repo=${fields[*]:2}
    repo=${repo// /\/} # Spaces back to / directory separator
    ;;
esac

# Remove tidle ~
org=${org/\~/}

user='git'
short_org=$org
case $org in
  input-output-hk) short_org='io';;
  io) org='input-output-hk';;
  ModusCreateOrg) short_org='modus';;
  modus) org='ModusCreateOrg';;
esac

cd "${SHELLY_CODE_DIR}"
git clone "${user}@${host}:${org}/${repo}" "${short_org}/${repo}"
