#!/usr/bin/env bash

set -euo pipefail

script=$(basename "$0")

Usage() {
  echo "usage: $script export|import|copy HOST" >&2
  exit 2
}

[[ $# -lt 1 ]] && Usage

command=$1; shift

key=1D9A17DFD23DCB91

if [[ $command == export ]]; then
  [[ $# -ne 0 ]] && Usage
  gpg --output git-gpg-key-pub.gpg --armor --export $key
  gpg --output git-gpg-key-sec.gpg --armor --export-secret-key $key
elif [[ $command == import ]]; then
  [[ $# -ne 0 ]] && Usage
  gpg --import git-gpg-key-pub.gpg
  gpg --allow-secret-key-import --import git-gpg-key-sec.gpg
elif [[ $command == copy ]]; then
  [[ $# -ne 1 ]] && Usage
  host=$1
  git-signing-key export
  rsync-mv git-gpg-key-*.gpg "${host}:"
  ssh "$host" 'source .profile; git-signing-key import'
  ssh "$host" 'rm git-gpg-key-*.gpg'
else
  Usage
fi
