#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 hash dir"
  exit 2
fi

gist_id=${1#https://gist.github.com/*/}
gist_id=${gist_id#https://gist.github.com/}
dir=$2

if false; then
  root=${SHELLY_CODE_DIR}/${USER}
  cd "$root"
fi

gh gist clone "${gist_id}" "${dir}"
