#!/usr/bin/env bash

set -euo pipefail
set -x

#
# Google Chrome
#
curl -sS https://dl.google.com/linux/linux_signing_key.pub |
  sudo apt-key add -
echo "deb https://dl.google.com/linux/chrome/deb/ stable main" |
  sudo tee -a /etc/apt/sources.list.d/google-chrome.list
sudo apt-get update -qqy
sudo apt-get -qqy install google-chrome-stable
