#!/usr/bin/env bash

set -euo pipefail

osType=$(uname)

echo 'Installing python neovim package...'

case $osType in
  Linux|Darwin)
    pip3 install --upgrade pip
    pip3 install neovim
    ;;
  *)
    echo "Unsupported OS $osType"
    exit 1
esac
