#!/usr/bin/env bash

set -euo pipefail

kubectl get pods \
    "$@" \
    --field-selector=status.phase=Running \
    -o='custom-columns=Node:.spec.nodeName,Namespace:.metadata.namespace,Name:.metadata.name' \
    --sort-by='.spec.nodeName' \
    --no-headers \
    "$@"
