#!/usr/bin/env bash

set -euo pipefail

from_namespace=$1
to_namespace=$2
secret_name=$3

delete_extra_metadata() {
  jq 'del(
        .metadata.namespace,
        .metadata.creationTimestamp,
        .metadata.resourceVersion,
        .metadata.selfLink,
        .metadata.uid
        )'
}

kubectl --namespace="${from_namespace}" get secrets "${secret_name}" -o json |
  delete_extra_metadata |
  kubectl --namespace="${to_namespace}" apply -f -
