#!/usr/bin/env bash

set -euo pipefail

pkgs_home="${SHELLY_HOME}/nix"

if [[ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
  multiUser='true'
else
  multiUser='false'
fi
# Install user packages.
nix-env \
  --file "${pkgs_home}" \
  --arg multiUser $multiUser \
  --install --remove-all \
  --attr userPackages \
  "$@"
