#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "$0")

function usage {
  echo "usage: $script_name [mobile|ipad|kindle] filename" >&2
  exit 2
}

if [[ $# -ne 2 ]]; then
  usage
fi

device_type=$1; shift
file=$1; shift

if [[ $device_type == 'mobile' ]]; then
  device='-w 720p -h 1280p -dpi 294'
elif [[ $device_type == 'ipad' ]]; then
  device='-w 768p -h 1024p -dpi 132'
elif [[ $device_type == 'kindle' ]]; then
  device='-w 1236p -h 1648p -dpi 300'
else
  Usage
fi

# shellcheck disable=SC2086
k2pdfopt \
  $device \
  -col 1 \
  -om 0.2 \
  -c \
  -bpc 8 \
  -fc- \
  -x \
  -ui- \
  -o "%s-$device_type" \
  "$@" \
  "$file"
