#!/usr/bin/env bash
#
# Generating high-quality portable PDF files from PostScript files.
# Helpful for converting PostScript papers to PDF for online reading.
#
# See http://www.volkerschatz.com/tex/hiqpdf.html
#

set -euo pipefail

ps2pdf -sPAPERSIZE=a4 -dCompatibilityLevel=1.3  \
 -dEmbedAllFonts=true -dSubsetFonts=true -dMaxSubsetPct=100  \
 -dAutoFilterColorImages=false -dColorImageFilter=/FlateEncode  \
 -dAutoFilterGrayImages=false -dGrayImageFilter=/FlateEncode  \
 -dAutoFilterMonoImages=false -dMonoImageFilter=/CCITTFaxEncode \
 "$@"
