#!/usr/bin/env bash

set -eu

if [[ $# -eq 0 ]]; then exec rsync; fi

exec rsync \
  --rsync-path=~/.nix-profile/bin/rsync \
  --progress \
  --verbose \
  --archive \
  --update \
  --compress \
  --hard-links \
  --xattrs \
  "$@"
