#!/usr/bin/env bash

set -euo pipefail

echo Bootstrapping shelly...

script_name='bootstrap'

if [[ -n ${SHELLY_HOME+unset} ]]; then
  echo "${script_name}: SHELLY_HOME already defined" >&2
  exit 1
fi

hash git || (
  echo "${script_name}: Please ensure git is installed" >&2
  exit 1
)
hash stow || (
  echo "${script_name}: Please ensure stow is installed" >&2
  exit 1
)

export SHELLY_CODE_DIR=~/Code
export SHELLY_HOME=${SHELLY_CODE_DIR}/steshaw/shelly

if [[ ! -d $SHELLY_HOME ]]; then
  git clone https://github.com/steshaw/shelly.git "$SHELLY_HOME"
fi

$SHELLY_HOME/script/shelly-link-home-files

echo
echo 'Source .profile or start a new shell to get started.'
