#!/usr/bin/env bash
#
# Slugify all files
#

set -euo pipefail

if [[ $(uname) == 'Darwin' ]]; then
  mv=/bin/mv
else
  mv='mv'
fi

for file_path in "$@"; do
  output=$file_path

  # Remove some characters.
  output=$(echo "$output" | tr -d \'\"\!\(\)\®)

  # Replace other punctuation with dashes.
  output=${output//[,;:]/-}

  # PascalCase to lisp-case.
  output=$(echo "$output" | perl -pe 's/([a-z0-9])([A-Z])/$1_\L$2/g')

  # Remove newlines.
  output=$(echo "$output" | tr -d '\n')

  # Compress spaces.
  output=$(echo "$output" | tr -s ' ')

  # Endash+emdash to dash.
  output=${output//–/-}
  output=${output//–/-}

  # Underscores to dash.
  output=${output//_/-}

  # Plus to dash.
  output=${output//+/-}

  # Remove spaces next to dashes.
  output=${output//- /-}
  output=${output// -/-}

  # Spaces to dashes
  output=$(echo "$output" | tr ' ' '-')

  # lowercase
  output=${output,,}

  if [[ "$file_path" != "$output" ]]; then
    $mv -iv "${file_path}" "${output}"
  fi
done
