#!/usr/bin/env bash

if [[ -r ~/.nix-profile/etc/ssl/certs/ca-bundle.crt ]]; then
  export SSL_CERT_FILE=~/.nix-profile/etc/ssl/certs/ca-bundle.crt
  export GIT_SSL_CAINFO=~/.nix-profile/etc/ssl/certs/ca-bundle.crt
fi
