# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ahci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = pkgs.lib.mkForce
    { device = "/dev/disk/by-uuid/827143d1-e83c-4c77-99bd-a6ede1408008";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  nix.maxJobs = 1;
  services.virtualboxGuest.enable = true;
}
