#!/usr/bin/env bash

set -euo pipefail

pkg=$1

echo Uninstalling $pkg ...
brew uninstall $pkg
deps=$(join <(brew leaves) <(brew deps $pkg))
if [[ -z $deps ]]; then
  echo No dependencies
else
  echo Uninstalling dependencies $deps ...
  brew uninstall $deps
fi
