#!/usr/bin/env bash

set -euo pipefail

if true; then
#    --alternate-editor='emacs -nw' \
  emacsclient \
    --no-wait \
    --socket-name=/tmp/emacs1000/server \
    "$@"
else
  emacsclient \
    --no-wait \
    --alternate-editor='emacs -nw' \
    "$@"
fi
