#!/usr/bin/env bash
#
# Rename given files with modification date.
#
# e.g. foo.txt -> 2019-10-01-foo.txt
#

set -euo pipefail

for file in "$@"; do
  mv -i "${file}" $(stat --format=%y "${file}" | cut -c1-10)-"${file}"
done
