#!/usr/bin/env bash


key_type='ed25519'

file="id_${key_type}"
postfix=''
if [[ $# -eq 1 ]]; then
  postfix="-$1"
  file="$1_${key_type}"
fi

ssh-keygen -f "${file}" -t ed25519 -b 4096 -C "${USER}@$(hostname -s)${postfix}"
