#!/usr/bin/env bash

set -euo pipefail

branch=$1
default_branch=$(git-default-branch)

git branch --delete "${branch}" || (
  git checkout "${branch}"
  git rebase "origin/${default_branch}"
  git checkout "${default_branch}"
  git branch --delete "${branch}"
)
