#!/usr/bin/env bash

set -euo pipefail

root=${SHELLY_DEV_DIR}

if [[ $# -ne 1 ]]; then
  echo "usage: $0 repo (i.e. leanprover/lean)"
  exit 2
fi

repoPath=${1#https://github.com/}

IFS=/ read -r -a fields <<<"$repoPath"
case ${#fields[@]} in
  1)
    user=${USER}
    repo=${fields[0]}
    ;;
  2)
    user=${fields[0]}
    repo=${fields[1]}
    ;;
  *)
    echo "Invalid repo path: $repoPath" >&2
    exit 2
esac

cd "$root"
git clone "git@github.com:$user/$repo" "$user/$repo"
