#!/usr/bin/env bash

set -euo pipefail

branch=$1
if [[ $# -eq 2 ]]; then
  default_branch=$2
else
  default_branch=$(git branch --show-current)
fi

git branch --delete "${branch}" || (
  git checkout "${branch}"
  git rebase "origin/${default_branch}"
  git checkout "${default_branch}"
  git branch --delete "${branch}"
)
