#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

#
# HT https://stackoverflow.com/a/10548919/482382
#

script=$(basename "$0")
if [[ $# -ne 2 || $1 == '--help' ]]; then
  echo "usage: ${script} /path/to/other/repo branch"
  exit 2
fi

other_repo_path=$1
branch=$2
remote_name=$(basename "${other_repo_path}")

git remote add "${remote_name}" "${other_repo_path}"
git fetch "${remote_name}" --tags
git merge --allow-unrelated-histories "${remote_name}/${branch}"
git remote remove "${remote_name}"
