#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 repo (i.e. leanprover/lean)"
  exit 2
fi

repo_path=${1#https://}
repo_path=${repo_path#git@}
repo_path=${repo_path%.git}
repo_path=${repo_path%/}
repo_path=${repo_path/://}
repo_path=${repo_path%*/*/*/}

IFS=/ read -r -a fields <<<"$repo_path"
case ${#fields[@]} in
  1)
    host='github.com'
    org=${USER}
    repo=${fields[0]}
    ;;
  2)
    host='github.com'
    org=${fields[0]}
    repo=${fields[1]}
    ;;
  *)
    host=${fields[0]}
    org=${fields[1]}
    repo=${fields[2]}
    echo "Discarding ${fields[*]:3}" >&2
    ;;
esac

user='git'
short_org=$org
case $org in
  sbsaustralia)
    host='bitbucket.org'
    short_org='sbs';;
  sbs)
    host='bitbucket.org'
    org='sbsaustralia';;
  input-output-hk) short_org='iohk';;
  iohk) org='input-output-hk';;
  mlabs-haskell) short_org='mlabs';;
  mlabs) org='mlabs-haskell';;
  ArdanaLabs) short_org='ardana';;
esac

cd "${SHELLY_DEV_DIR}"
git clone "${user}@${host}:${org}/${repo}" "${short_org}/${repo}"
