#!/usr/bin/env bash

set -euo pipefail

branch=$1

git branch --delete "${branch}" || (
  git checkout "${branch}"
  git rebase origin/master
  git checkout master
  git branch --delete "${branch}"
)
