#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 0 ]]; then
  echo "usage: git-open"
  exit 2
fi

url=$(git remote get-url origin)

case $url in
  http*)
    echo Opening "$url ..."
    o "$url"
    ;;
  git@* | gist.*)
    url=http://$(echo "$url" | perl -pe 's/gis?t@//; s-:-/-; s/\.git$//;')
    echo "Opening $url ..."
    o "$url"
    ;;
  *)
    echo "Unable to open origin $url"
    exit 1
esac
