#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "${0}")
title="${USER}@$(hostname) (added by ${script_name})"
key="$(cat ~/.ssh/id_rsa.pub)"

curl \
  -X POST \
  -H "Authorization: token ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/user/keys \
  -d "{\"title\": \"${title}\", \"key\": \"${key}\""\
