#!/usr/bin/env bash

set -euo pipefail

opt_dir=~/.shelly/opt
mkdir -p ${opt_dir}
cd ${opt_dir}

os=$(uname)
os=${os,,} # lowercase
if [[ $os == darwin ]]; then
  arch='arm64'
else
  # Just presume Intel/AMD.
  arch='amd64'
fi

version=${1#go}
tarball="go${version}.${os}-${arch}.tar.gz"
url="https://golang.org/dl/${tarball}"

curl --continue-at - -L -o "${tarball}" "${url}" || true

install_dir="go-${version}"
mkdir -p "${install_dir}"
tar -x -C "${install_dir}" --strip-components=1 -f "${tarball}"
