#!/usr/bin/env bash

set -euo pipefail

install_dir=~/.shelly/opt
mkdir -p ${install_dir}
cd ${install_dir}

os=$(uname)
os=${os,,} # lowercase
if [[ $os == darwin ]]; then
  arch='arm64'
else
  # Just presume Intel/AMD.
  arch='amd64'
fi

version=${1#go}
tarball="go${version}.${os}-${arch}.tar.gz"
url="https://golang.org/dl/${tarball}"
dir="go-${version}"

mkdir "${dir}"
curl --continue-at - -L -o "${tarball}" "${url}" || true
tar -x -C "${dir}" --strip-components=1 -f "${tarball}"
