#!/usr/bin/env bash

set -euo pipefail

file=$1

input=${file}.pdf
output=${file}.inverted.pdf

gs -o "${output}" \
   -sDEVICE=pdfwrite  \
   -c "{1 exch sub}{1 exch sub}{1 exch sub}{1 exch sub} setcolortransfer" \
   -f "${input}"
