#!/usr/bin/env bash

set -euo pipefail

script=$(basename "$0")
if [[ $# -ne 1 ]]; then
  echo "usage: $script namespace" >&2
  exit 2
fi

namespace=$1; shift

kubectl config set-context "$(kubectl config current-context)" \
  --namespace="$namespace"
