#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 || $1 == '--help' || $1 == '-h' ]]; then
  script_name=$(basename "$0")
  echo "Usage: ${script_name} SECRET_NAME KEY"
  exit 2
fi

secret_name=$1
key=$2

kubectl get secret "${secret_name}" -o jsonpath="{.data.${key}}" |
  base64 --decode
echo
