#!/usr/bin/env bash

set -euo pipefail

if [[ $(uname) == Darwin ]]; then
  sudo -i sh -x -c '
    nix-channel --update &&
      nix-env -iA nixpkgs.nixUnstable &&
      launchctl remove org.nixos.nix-daemon &&
      launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist'
else
  set -x
  sudo systemctl restart nix-daemon.service
fi
