#!/usr/bin/env bash

set -euo pipefail
${SCRIPT_DEBUG:-}

export NIX_PATH="nixpkgs=${SHELLY_HOME}/nix"
if [[ -x ~/.nix-profile/bin/nix-rebuild ]]; then
  if [[ $# -eq 1 && ( $1 == '--dry-run' || $1 == '-n' ) ]]; then
    nix-what-rebuild
  else
    ~/.nix-profile/bin/nix-rebuild
  fi
else
  nix-env --install --remove-all --attr userPackages "$@"
fi
