#!/usr/bin/env bash

set -euo pipefail

pkgs_home="${SHELLY_HOME}/nix"

if [[ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
  multiUser='true'
else
  multiUser='false'
fi
# Install user packages.
nix-env \
  --file "${pkgs_home}" \
  --arg multiUser $multiUser \
  --install --remove-all --attr userPackages "$@"

# Quick hack to install some packages that are broken on aarch64-darwin.
if [[ $(uname) == Darwin ]]; then
  # Ask niv for the nixpkgs tarball pin.
  nixpkgs_tarball=$(
    cd "${SHELLY_HOME}";
    jq -r .nixpkgs.url <nix/sources.json
  )

  nix-env --argstr system "x86_64-darwin" -f "$nixpkgs_tarball" --install \
    --attr cabal2nix --attr hledger --attr idris2 --attr niv --prebuilt-only
fi
