#!/usr/bin/env bash

set -euo pipefail

revision='9b3515eb95d9b3bc033f43cd562fe2b14f9efd86'
revision='10100a97c8964e82b30f180fda41ade8e6f69e41'
revision='6bcb1dec8ea16f20e6404631668cf69e76424eef'

base_url=https://github.com/nixos/nixpkgs/archive
url=${base_url}/${revision}.tar.gz

NIX_PATH=nixpkgs=${url} nix-env -f '<nixpkgs>' -r -iA userPackages "$@"

exit

#
# FIXME: Fix below which provides a diff but breaks with use of `super.recurseIntoAttrs` above.
#        The `super.recurseIntoAttrs` allows you to find userPackages when doing `nix search`.

set -e
IFS=- read -r _ oldGen _ <<<"$(readlink "$(readlink ~/.nix-profile)")"
oldVersions=$(readlink ~/.nix-profile/package_versions || echo "/dev/null")
nix-env -f '<nixpkgs>' -r -iA userPackages "$@"
IFS=- read -r _ newGen _ <<<"$(readlink "$(readlink ~/.nix-profile)")"
${self.diffutils}/bin/diff --color -u --label "generation $oldGen" $oldVersions \
  --label "generation $newGen" ~/.nix-profile/package_versions \
  || true
