#!/usr/bin/env bash

set -euo pipefail

pkgs_home="${SHELLY_HOME}/nix"

if [[ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
  multiUser='true'
else
  multiUser='false'
fi
# Install user packages.
nix-env \
  --file "${pkgs_home}" \
  --arg multiUser $multiUser \
  --install --remove-all --attr userPackages "$@"

# Install user packages on Darwin that are not available as
# aarch64-darwin.
if false && [[ $(uname) == Darwin ]]; then
  # Ask niv for the nixpkgs tarball pin.
  nixpkgs_tarball=$(
    cd "${SHELLY_HOME}";
    jq -r .nixpkgs.url <nix/sources.json
  )

  export NIX_PATH="nixpkgs=${nixpkgs_tarball}"
  nix-env -e nix-bash-completions
  nix profile install \
    nixpkgs#legacyPackages.x86_64-darwin.cabal2nix \
    nixpkgs#legacyPackages.x86_64-darwin.hledger \
    nixpkgs#legacyPackages.x86_64-darwin.idris2 \
    nixpkgs#legacyPackages.x86_64-darwin.niv \
    #
fi
