#!/usr/bin/env bash

set -euo pipefail

pkg=$1

nix-instantiate \
    --argstr pkg "${pkg}" \
    --eval \
    --strict \
    --json \
    --expr '({pkg}: (import ./nixpkgs-versions.nix {inherit pkg ;}))' | jq
