#!/usr/bin/env bash

set -euo pipefail

if [[ -x "$(type -p gnome-open 2>&-)" ]]; then
  command=gnome-open
elif [[ -x "$(type -p firefox 2>&-)" ]]; then
  command=firefox
elif [[ -x "$(type -p xdg-open 2>&-)" ]]; then
  command=xdg-open
elif [[ -x "$(type -p open 2>&-)" ]]; then
  command=open
else
  alias o=echo
fi

$command "$@"
