#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

if [[ -x "$(type -p xdg-open 2>&-)" ]]; then
  command=xdg-open
elif [[ ${SHELLY_OS} == darwin && -x "$(type -p open 2>&-)" ]]; then
  command=open
elif [[ -x "$(type -p gnome-open 2>&-)" ]]; then
  command=gnome-open
elif [[ -x "$(type -p firefox 2>&-)" ]]; then
  command=firefox
else
  echo "echo find program to open open $*" >&2
  exit 1
fi

$command "$@"
