#!/usr/bin/env bash

set -euo pipefail

function printPath {
  tr : '\n' | perl -pe 's/^/  /'
}

echo PATH:
echo "$PATH" | printPath
if [[ ${NIX_PATH:-unset} != unset ]]; then
  echo
  echo NIX_PATH:
  echo "$NIX_PATH" | printPath
fi
if [[ ${LD_LIBRARY_PATH:-unset} != unset ]]; then
  echo
  echo LD_LIBRARY_PATH:
  echo "$LD_LIBRARY_PATH" | printPath
fi
if [[ ${DYLD_LIBRARY_PATH:-unset} != unset ]]; then
  echo
  echo DYLD_LIBRARY_PATH:
  echo "$DYLD_LIBRARY_PATH" | printPath
fi
