#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

default_resolution=133

usage() {
  script=$(basename "$0")
  cat <<! >&2
usage: $script input-file [resolution]

resolution    e.g. 72 or 150 (default ${default_resolution})
!
  exit 2
}

[[ $# -eq 0 || $# -gt 2 ]] && usage

input_file=$1
resolution=${2:-${default_resolution}}

output_file=$(basename "${input_file}" .pdf).compressed.pdf

shrinkpdf "${input_file}" "${output_file}" "${resolution}"

ls -lh "${input_file}" "${output_file}"
