#!/usr/bin/env bash

set -euo pipefail

if [[ $(uname) == Darwin ]]; then
  echo 'Brewing ...'
  brew bundle --global
fi

if [[ -n $NIX_PROFILES ]]; then
  echo 'Installing Nix user packages ...'
  nix-rebuild
fi
