#!/usr/bin/env bash

set -euo pipefail

if [[ $(uname) == Darwin ]]; then
  echo 'Brewing ...'
  brew bundle --global
fi

echo 'Installing Nix user packages ...'
nix-rebuild

echo 'Doing myrepos checkout ...'
mr --directory "$HOME" checkout
