#!/usr/bin/env bash

set -euo pipefail

repo=$1

features=(
  issues
  pulls
  statuses
  commits
  deployments
  public
  releases
  reviews
  comments
  branches
  commits:all
)

printf -v a '%s,' "${features[@]}"
comma_sep_features="${a%,}"

echo "/github subscribe ${repo} ${comma_sep_features}"
