#!/usr/bin/env bash

set -euo pipefail

os=$(uname)

case $os in
  Darwin)
    if command -v gtime >/dev/null; then
      gtime -v "$@"
    else
      /usr/bin/time -l "$@"
    fi
    ;;
  Linux)
    $(type -P time) -v "$@"
    ;;
  *)
    echo "Warning: no t for $os"
esac
