#!/usr/bin/env bash

if has starship; then
  function set_win_title(){
    cwd=$(echo $PWD | sed "s@^$HOME@~@")
    echo -ne "\033]0;${USER}@${HOSTNAME}:${cwd}\007"
  }
  starship_precmd_user_func="set_win_title"
  eval "$(starship init bash)"
else
  source $(dirname "${BASH_SOURCE[0]}")/prompt.custom.disabled
fi
