templates:
  params:
    author-name: Steven Shaw
    author-email: steven@steshaw.org
    # Using "license" here does not work. We'd need to provide an alternative
    # LICENCE file anyhow...
    license: MIT
    copyright: (c) 2019, Steven Shaw
    github-username: steshaw
    category: Example
