#!/bin/sh

if has docker-machine; then
  eval "$(docker-machine env 2>/dev/null)"
fi

_main() {
  if isZsh || isBash; then
    isZsh && shell=zsh
    isBash && shell=bash

    dockerEtc=/Applications/Docker.app/Contents/Resources/etc

    has docker && sourceExists "${dockerEtc}/docker.${shell}-completion"
    has docker-machine && sourceExists "${dockerEtc}/docker-machine.${shell}-completion"
    has docker-compose && sourceExists "${dockerEtc}/docker-compose.${shell}-completion"
  fi
}
_main
unset -f _main
