#!/bin/sh

alias use-brittany='(cd ~/.local; ln -fs $SHELLY_HOME/script/hindent-brittany-adapter ~/.local/bin/hindent)'
alias use-ormolu='(cd ~/.local; ln -fs $SHELLY_HOME/script/hindent-ormolu-adapter ~/.local/bin/hindent)'
