#!/bin/sh

if [ -n "$ZSH_VERSION" ]; then
  test -r ~/.opam/opam-init/init.zsh &&
    . ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
else
  test -r ~/.opam/opam-init/init.sh &&
    . ~/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
fi
