#!/usr/bin/env bash

if has direnv; then
  if isZsh; then
    eval "$(direnv hook zsh)"
  elif isBash; then
    eval "$(direnv hook bash)"
  else
    Echo "Warning: direnv not configured for your shell"
  fi
fi
