#!/usr/bin/env bash

prependPaths ~/.cabal/bin ~/.ghcup/bin

# XXX: Probably don't need these any more.
#alias ghc-sandbox="ghc -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
#alias ghci-sandbox="ghci -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
#alias runhaskell-sandbox="runhaskell -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"

# ex: filetype=sh tabstop=20 shiftwidth=2 expandtab
